[rpc_and_lcd_endpoints]
skale_node_ip = 88.99.66.228:3009

[telegram]
tg_chat_id = 228281095
tg_bot_token = "1117273891:AAEtr3ZU5x4JRj5YSF4LBeu1fPF0T4xj-UI"


[sendgrid]
sendgrid_token = "SG.J4dl16RST9OM9Nc2Tbvh6A.L_FPSzlqvBesPPQP72hATEt5Hs8TUzo9Dl3ohG8Rk"
receiver_email_address = "xyz@example.com"
account_email = "xyz@domain.com"
sendgrid_account_name = "xyz"

[prometheus]
listen_address = ":9000"
prometheus_address = "http://localhost:9090"