{
 "title": "Skale Validator Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skale_block_number" }
   ]
  },
  {
   "title": "SGX Wallet Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skale_sgx_status", "legendFormat": "{{status_name}}" }
   ]
  },
  {
   "title": "SGX Wallet Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skale_sgx_status", "legendFormat": "{{wallet_version}}" }
   ]
  },
  {
   "title": "BTRFS kernal module status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "btrfs_status", "legendFormat": "{{btrfs_status}}" }
   ]
  },
  {
   "title": "Status Core Info",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "skale_core_status" }
   ]
  },
  {
   "title": "Hardware Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "hardware_info" }
   ]
  }
 ]
}