{
 "title": "Skale Validator Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skale_block_number" }
   ]
  },
  {
   "title": "Public IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skale_public_ip", "legendFormat": "{{public_ip}}" }
   ]
  },
  {
   "title": "SGX Wallet Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skale_sgx_status", "legendFormat": "{{status_name}}" }
   ]
  },
  {
   "title": "SGX Wallet Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "skale_sgx_status", "legendFormat": "{{wallet_version}}" }
   ]
  },
  {
   "title": "BTRFS kernal module status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "btrfs_status", "legendFormat": "{{btrfs_status}}" }
   ]
  },
  {
   "title": "Status Core Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "skale_core_status" }
   ]
  },
  {
   "title": "Hardware Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "hardware_info" }
   ]
  }
 ]
}